# OSV Scanner Configuration File

# Scanning options
[scan]
# Determine if dev dependencies should be scanned
dev-dependencies = true

# Set to skip scanning specific ecosystem
# Supported: "go", "npm", "oss-fuzz", "pypi", "maven", "cargo", "nuget", "composer", "hex"
# Example: skip = ["npm", "composer"]
# skip = []

# Configure vulnerability filtering
[vulnerability]
# Ignore specific vulnerability IDs
# Example: ignore = ["GO-2022-0968", "GHSA-abcd-1234-5678"]
ignore = []

# Database download and caching behavior
[database]
# Control the local cache directory for OSV databases
cache-dir = ".osv-scanner-cache"

# Define custom database sources to use
# [[database.source]]
# name = "custom-source"
# uri = "file:///path/to/custom/database"

# Use this for experiments or to define overrides
[experiments]
# Vulnerability overrides for special cases
# [[experiments.vulnerability-overrides]]
# id = "GO-2022-0968"
# fixed = "1.17.13"
# note = "Custom override for special case"
