# Trivy Ignore Rules

# This is an example configuration for ignoring vulnerabilities with more granular control
ignoreRules:
  - vulnerability: CVE-2020-12345
    package: express
    version: 4.17.1
    reason: "Fixed in our custom implementation"
    expiry: 2025-12-31
  
  - vulnerability: GHSA-abcd-1234-5678
    package: lodash
    reason: "Not exploitable in our context"

  # Ignore all vulnerabilities of a package
  - package: legacy-app
    reason: "Deprecated, scheduled for removal"
    expiry: 2025-10-31
