name: Grype Comprehensive Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  scan:
    name: Full Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install latest versions of Grype and Syft
      - name: Install Grype
        uses: anchore/scan-action/download-grype@v3
        with:
          grype-version: "latest"

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0
        with:
          syft-version: "latest"

      # Build container if Dockerfile exists
      - name: Build container image
        id: build-image
        run: |
          if [ -f "Dockerfile" ]; then
            docker build -t grype-full-scan:${{ github.sha }} .
            echo "image_built=true" >> $GITHUB_OUTPUT
          else
            echo "image_built=false" >> $GITHUB_OUTPUT
          fi

      # Scan container image if built
      - name: Scan container image
        if: steps.build-image.outputs.image_built == 'true'
        run: |
          grype image:grype-full-scan:${{ github.sha }} -c grype-security-setup/configs/grype-config.yaml -o sarif > grype-container-full.sarif

      # Generate SBOM
      - name: Generate SBOM
        run: |
          syft dir:. -o cyclonedx-json > sbom-full.cyclonedx.json

      # Scan filesystem
      - name: Scan filesystem
        run: |
          grype dir:. -c grype-security-setup/configs/grype-config.yaml -o sarif > grype-fs-full.sarif

      # Scan SBOM
      - name: Scan SBOM
        run: |
          grype sbom:sbom-full.cyclonedx.json -c grype-security-setup/configs/grype-config.yaml -o sarif > grype-sbom-full.sarif

      # Merge scan results
      - name: Combine scan results
        run: |
          echo '{"version":"2.1.0","runs":[]}' > grype-combined.sarif
          
          for file in grype-*-full.sarif; do
            if [ -f "$file" ]; then
              jq -s '.[0].runs = (.[0].runs + .[1].runs) | .[0]' grype-combined.sarif "$file" > temp.sarif
              mv temp.sarif grype-combined.sarif
            fi
          done

      # Upload combined results
      - name: Upload combined scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-combined.sarif
          category: grype-comprehensive

      # Archive artifacts
      - name: Archive scan results
        uses: actions/upload-artifact@v3
        with:
          name: grype-scan-results
          path: |
            grype-*.sarif
            sbom-full.cyclonedx.json
          retention-days: 7
