name: Grype Filesystem Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  scan:
    name: Filesystem Vulnerabilities Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Grype
        uses: anchore/scan-action/download-grype@v3
        with:
          grype-version: "latest"
          
      - name: Scan filesystem for vulnerabilities
        id: scan
        run: |
          grype dir:. -o sarif > grype-fs-results.sarif

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-fs-results.sarif
          category: grype-filesystem
