name: Gitleaks Secret Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to scan all commits

      - name: Gitleaks Action
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_CONFIG: gitleaks-security-setup/configs/gitleaks.toml

      - name: Run Gitleaks with SARIF output
        id: gitleaks-sarif
        if: success() || failure()  # Run regardless of Gitleaks Action status
        run: |
          # Install Gitleaks
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sh -s -- -b /usr/local/bin
          
          # Create output directory
          mkdir -p gitleaks-results
          
          # Run scan with SARIF output
          gitleaks detect --source . \
            --config=gitleaks-security-setup/configs/gitleaks.toml \
            --report-format=sarif \
            --report-path=gitleaks-results/results.sarif \
            --no-git \
            --verbose
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gitleaks-results/results.sarif
          category: gitleaks-secrets
