repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-merge-conflict

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
  - id: gitleaks

- repo: https://github.com/pycqa/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["-r", "src", "-c", ".bandit.yaml"]

- repo: https://github.com/returntocorp/semgrep
  rev: v1.21.0
  hooks:
  - id: semgrep
    args: ["--config", "auto", "--error"]

- repo: local
  hooks:
  - id: security-check
    name: security-check
    entry: python .github/scripts/pre_commit_security_check.py
    language: python
    additional_dependencies: [requests, pyyaml]
    always_run: true
