# Grype configuration file
# See full reference at: https://github.com/anchore/grype#configuration

# Ignore CVEs matching criteria
ignore:
  # - vulnerability: CVE-2021-12345
  # - vulnerability: CVE-2022-67890
  #   package:
  #     name: some-package
  #     version: 1.2.3

# Match vulnerability findings against fixes
match:
  # Use CPE match for better vulnerability detection
  packages: 
    - golang
    - python
    - javascript
    - java
  
# Set output formats
output:
  # Set the default output format
  format: table
  
  # Configure format-specific options
  template: ""
  
  # Include full vulnerability details
  show-suppressed: false

# Configure scan scope
search:
  # Maximum depth to search for packages
  scope: "squashed"
  
  # File exclusion globs
  excluded-paths:
    - "**/.git/**"
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/tests/**"
    - "**/__pycache__/**"

# DB cache settings
db:
  cache-dir: ".grype-cache"
  update-url: "https://toolbox-data.anchore.io/grype/databases/listing.json"
  auto-update: true

# Analysis logging and output settings  
log:
  level: "warn"
  file: ""
  structured: false

# Fail the scan at given severity level
fail-on-severity: "critical"

# Determine what types of dependencies to include
package:
  catalogs:
    from-cyclonedx: true
  
  # How many levels deep to search for dependencies
  search-unindexed-archives: true
  search-indexed-archives: true
