name: Scheduled Trivy Scan

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:

jobs:
  scan:
    name: Comprehensive Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Scan container images if they exist
      - name: Build images from Dockerfiles
        run: |
          for dockerfile in $(find . -name "Dockerfile" -o -name "*.dockerfile"); do
            dir=$(dirname $dockerfile)
            name=$(basename $dir)
            echo "Building image from $dockerfile as $name"
            docker build -t $name:scan -f $dockerfile $dir || true
          done

      # Run Trivy on all built images
      - name: Scan container images
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-images-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          timeout: '15m'
        continue-on-error: true

      # Run Trivy on filesystem
      - name: Scan filesystem for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-full-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          timeout: '15m'
        continue-on-error: true

      # Combine SARIF files
      - name: Combine SARIF files
        run: |
          echo '{"version":"2.1.0","runs":[]}' > trivy-combined-results.sarif
          for file in trivy-*-results.sarif; do
            if [ -f "$file" ]; then
              # Extract runs array from each file and append to the combined file
              jq -s '.[0].runs + .[1].runs | {"version":"2.1.0", "runs":.}' trivy-combined-results.sarif $file > temp.sarif
              mv temp.sarif trivy-combined-results.sarif
            fi
          done

      # Upload combined results
      - name: Upload combined scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-combined-results.sarif'
          category: 'trivy-comprehensive'
