name: TruffleHog Secret Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to scan all commits

      - name: TruffleHog OSS Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified --json

      - name: Run TruffleHog with SARIF output
        id: trufflehog-sarif
        run: |
          # Install TruffleHog
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          
          # Create output directory
          mkdir -p trufflehog-results
          
          # Run scan with SARIF output
          trufflehog git file://. --since-commit HEAD~100 --branch HEAD --fail --no-update --only-verified --sarif > trufflehog-results/results.sarif
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || steps.trufflehog-sarif.outcome == 'failure'
        with:
          sarif_file: trufflehog-results/results.sarif
          category: trufflehog-secrets
