name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 # This example uses Node.js
        with:
          node-version: '20'

      - name: Build project
        run: npm run build ## EDIT THIS with your project's build command ##

      - name: Create Zip File
        run: zip -r my-app.zip ./dist ## EDIT THIS with your app name and output folder ##

      - name: Upload Zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./my-app.zip
          asset_name: my-app.zip
          asset_content_type: application/zip