name: Semgrep Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  semgrep-scan:
    name: Semgrep Static Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Semgrep
        run: |
          # Run Semgrep with full rule set and output to SARIF format
          semgrep ci \
            --config=auto \
            --config=semgrep-security-setup/configs/semgrep-rules.yaml \
            --sarif --output=semgrep-results.sarif \
            --metrics=off \
            --verbose
        env:
          SEMGREP_RULES: p/default p/security-audit p/owasp-top-ten p/cwe-top-25 p/supply-chain
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep
